---
- name: Installing Pre-Reqs for Debian/Ubuntu
  apt:
    name: "{{ modsecurity.dependencies }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Save the current list of packages for Debian/Ubuntu
  shell: dpkg-query -l > /tmp/before.txt
  when: ansible_os_family == "Debian" and ( modsecurity.packages_keep is undefined or not modsecurity.packages_keep )

- name: Installing compiler dependencies for Debian/Ubuntu
  apt:
    name: "{{ modsecurity.build_dependencies }}"
    state: present
  when: ansible_os_family == "Debian"

- name: get the rpm or apt package facts
  package_facts:
    manager: "auto"

- name: Record nginx version
  set_fact:
    nginx_modsec3_crs3_nginx_version: "{{ ansible_facts.packages.nginx[0].version.split('-')[0] }}"

- name: Compile ModSecurity3 and install OWAPS CRS3
  include: compile.yml

- name: Check which packages were installed for Debian/Ubuntu
  shell: dpkg-query -l > /tmp/after.txt
  when: ansible_os_family == "Debian" and ( modsecurity.packages_keep is undefined or not modsecurity.packages_keep )

- name: Create a list of installed packages
  shell: diff /tmp/before.txt /tmp/after.txt|awk '/>/{print $3}'
  register: installed
  when: modsecurity.packages_keep is undefined or not modsecurity.packages_keep

- name: Remove installed packages for compiling
  package:
    name: "{{ installed.stdout_lines }}"
    state: absent
  when: installed is defined and (modsecurity.packages_keep is undefined or not modsecurity.packages_keep)
